#!/bin/bash
sudo apt update
sudo apt install apache2 php php-mbstring mariadb-server php-mysql libapache2-mod-php git
sudo chown -R pi:www-data /var/www/html/
sudo chmod -R 770 /var/www/html/
cd /var/www/html
git clone https://github.com/Firexlator/mysql

